# Generated by Django 5.2.5 on 2025-09-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0002_baraa"),
    ]

    operations = [
        migrations.AddField(
            model_name="baraa",
            name="price",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
