# Generated by Django 5.2.5 on 2025-09-16 08:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store_app", "0003_baraa_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="angilal",
            name="cat_img",
            field=models.ImageField(blank=True, upload_to="photos/categories"),
        ),
        migrations.AddField(
            model_name="angilal",
            name="description",
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="angilal",
            name="slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="baraa",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="baraa",
            name="description",
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="baraa",
            name="images",
            field=models.ImageField(blank=True, upload_to="photos/products"),
        ),
        migrations.AddField(
            model_name="baraa",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="baraa",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="baraa",
            name="slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="baraa",
            name="stock",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
